services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  
    networks:
      - app-network
  
  app:
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       DB_HOST: mongodb
     ports:
       - "3100:3100"
       - "7000:7000"
     depends_on:
       - mongodb
     networks:
       - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
